name: Build and publish

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout actions
      uses: actions/checkout@v4

    - name: Set up Azul Zulu 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven

    - name: Setup buildenv
      run: cp ./settings.xml $HOME/.m2/

    - name: Build packages
      run: mvn -B package --file pom.xml

    - name: Release Artifacts
      uses: softprops/action-gh-release@v0.1.15
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Javadocs for Discord"
        tag_name: "latest"
        target_commitish: ${{ github.ref_name }}
        generate_release_notes: true
        fail_on_unmatched_files: true
        files: target/*.jar
